### ISSUE TITLE
onfailure never called?

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [telly/groundy#53]
I'm sure this is due to lack of understnading rather than a bug(sorry).

I have a background method that does the following:

(RouteGenerationService.class)
 @Override
    protected TaskResult doInBackground() {
      retrieveRoute routeToPlot =  new retrieveRoute(start,distance);
              routeToPlot.getData();

        if(routeToPlot.getRoute() !=null) {
            return succeeded().add("route", routeToPlot.getRoute());
        }

        else
System.out.println("about to return a failure"); //this sysout is called.
        return failed();
    }

In the class I want to do something I have this :

  @OnSuccess(routeGenerationService.class)
    public void onSuccess(@Param("route") String result) {
        Toast.makeText(this, "did we actually manage this?", Toast.LENGTH_LONG).show();
    }

        @OnFailure(routeGenerationService.class)
    public void onFailure() {
                       System.out.println("I failed you");
        Toast.makeText(this, "Failed as expected, but at least it is doing something right?", Toast.LENGTH_LONG).show();

    }

I start my Groundy like this:
                    Groundy.create(routeGenerationService.class).callback(RunningMap.class).queueUsing(this);

Am I missing something? really appreciate any help.

**Comment by eveliotc** [comment]
@MatthewJamesBoyle callback needs to be an instance of the class you annotated with `@OnFailure` instead of its class itself, did you mean to use `this` instead?:

```java
Groundy.create(RouteGenerationService.class)
.callback(this) // or RunningMap.this
.queueUsing(this);
```

**Comment by MatthewJamesBoyle** [comment]
thank you for this- problem solved :)

**Comment by eveliotc** [comment]
Anytime!

**Comment by MatthewJamesBoyle** [comment]
Glad you said that;) 
Got it working now except I am trying to pass an ArrayList back to my UI thread with 
         return succeeded().add("route", routeToPlot.getRoute());

Can this be done?

**Comment by eveliotc** [comment]
@MatthewJamesBoyle you can only send as result whatever you can put in a `Bundle`, if you are going to send something on an `ArrayList` it must be a `CharSequence`, `String`, `Integer` or `implement Parcelable`. You should be able to send a `ArrayList<LatLng>` as [`LatLng`](http://developer.android.com/reference/com/google/android/gms/maps/model/LatLng.html) actually implements `Parcelable`, please let me know if that's not the case for you and fully qualified `LatLng` name in order to test.

**Comment by MatthewJamesBoyle** [comment]
Hi sorry only just logged in and seen this. I changed it so the result is sent back to a static object in my other other class.  Let me set my code up again and see if LatLng will work being passed back as a result.
